# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simply_useful}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maciej Bilas"]
  s.date = %q{2010-03-19}
  s.description = %q{A set of simply useful classes. Contains extensions to core Ruby classes.}
  s.email = %q{maciej@inszy.org}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION.yml",
     "lib/bsearch.rb",
     "lib/core_ext.rb",
     "lib/core_ext/hash.rb",
     "lib/format.rb",
     "lib/has_attributes.rb",
     "lib/java_native2ascii.rb",
     "lib/simply_useful.rb",
     "simply_useful.gemspec",
     "spec/bsearch_spec.rb",
     "spec/core_ext/hash_spec.rb",
     "spec/has_attributes_spec.rb",
     "spec/java_native2ascii_spec.rb",
     "spec/simply_useful_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/maciej/simply_useful}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{simply_useful}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A set of simply useful classes}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/simply_useful_spec.rb",
     "spec/core_ext/hash_spec.rb",
     "spec/bsearch_spec.rb",
     "spec/has_attributes_spec.rb",
     "spec/java_native2ascii_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

